src/Entity/Lieu.php
<?php

namespace App\Entity;

use App\Repository\LieuRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=LieuRepository::class)
 */
class Lieu
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=30, nullable=true)
     */
    private $rue;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $latitude;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $longitude;

    /**
     * @ORM\ManyToOne(targetEntity=Ville::class, inversedBy="lieu", cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $villes_no_ville;

    /**
     * @ORM\OneToMany(targetEntity=Sortie::class, mappedBy="lieux_noLieu")
     */
    private $sorties;



    public function __construct()
    {
        $this->sorties = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getRue(): ?string
    {
        return $this->rue;
    }

    public function setRue(?string $rue): self
    {
        $this->rue = $rue;

        return $this;
    }

    public function getLatitude(): ?float
    {
        return $this->latitude;
    }

    public function setLatitude(?float $latitude): self
    {
        $this->latitude = $latitude;

        return $this;
    }

    public function getLongitude(): ?float
    {
        return $this->longitude;
    }

    public function setLongitude(?float $longitude): self
    {
        $this->longitude = $longitude;

        return $this;
    }

    public function getVillesNoVille(): ?Ville
    {
        return $this->villes_no_ville;
    }

    public function setVillesNoVille(?Ville $villes_no_ville): self
    {
        $this->villes_no_ville = $villes_no_ville;

        return $this;
    }

    /**
     * @return Collection|sortie[]
     */
    public function getSorties(): Collection
    {
        return $this->sorties;
    }

    public function addSorty(sortie $sorty): self
    {
        if (!$this->sorties->contains($sorty)) {
            $this->sorties[] = $sorty;
            $sorty->setLieuxNoLieu($this);
        }

        return $this;
    }

    public function removeSorty(sortie $sorty): self
    {
        if ($this->sorties->removeElement($sorty)) {
            // set the owning side to null (unless already changed)
            if ($sorty->getLieuxNoLieu() === $this) {
                $sorty->setLieuxNoLieu(null);
            }
        }

        return $this;
    }
    public function __toString(){
        return $this->nom;
    }

}

src/Entity/Sortie.php
<?php

namespace App\Entity;

use App\Repository\SortieRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=SortieRepository::class)
 */
class Sortie
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $nom;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_debut;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $duree;

    /**
     * @ORM\Column(type="date")
     */
    private $date_cloture;

    /**
     * @ORM\Column(type="integer")
     */
    private $nb_inscriptions_max;

    /**
     * @ORM\Column(type="string", length=500, nullable=true)
     */
    private $description_infos;

    /**
     * @ORM\Column(type="string", length=250, nullable=true)
     */
    private $url_photo;

    /**
     * @ORM\ManyToOne(targetEntity=UserController::class, inversedBy="sortie")
     * @ORM\JoinColumn(nullable=false)
     */
    private $organisateur;

    /**
     * @ORM\ManyToOne(targetEntity=Etat::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $etats_no_etat;

    /**
     * @ORM\ManyToOne(targetEntity=Site::class, inversedBy="sorties")
     * @ORM\JoinColumn(nullable=false)
     */
    private $site_organisateur;

    /**
     * @ORM\ManyToOne(targetEntity=Lieu::class, inversedBy="sorties")
     * @ORM\JoinColumn(nullable=false)
     * @Assert\NotBlank()
     */
    private $lieux_noLieu;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(?string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(?\DateTimeInterface $date_debut): self
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDuree(): ?int
    {
        return $this->duree;
    }

    public function setDuree(?int $duree): self
    {
        $this->duree = $duree;

        return $this;
    }

    public function getDateCloture(): ?\DateTimeInterface
    {
        return $this->date_cloture;
    }

    public function setDateCloture($date_cloture): self
    {
        $this->date_cloture = $date_cloture;

        return $this;
    }

    public function getNbInscriptionsMax(): ?int
    {
        return $this->nb_inscriptions_max;
    }

    public function setNbInscriptionsMax(?int $nb_inscriptions_max): self
    {
        $this->nb_inscriptions_max = $nb_inscriptions_max;

        return $this;
    }

    public function getDescriptionInfos(): ?string
    {
        return $this->description_infos;
    }

    public function setDescriptionInfos(?string $description_infos): self
    {
        $this->description_infos = $description_infos;

        return $this;
    }

    public function getUrlPhoto(): ?string
    {
        return $this->url_photo;
    }

    public function setUrlPhoto(?string $url_photo): self
    {
        $this->url_photo = $url_photo;

        return $this;
    }

    public function getOrganisateur(): ?UserController
    {
        return $this->organisateur;
    }

    public function setOrganisateur(?UserController $organisateur): self
    {
        $this->organisateur = $organisateur;

        return $this;
    }

    public function getLieuxNolieu(): ?Lieu
    {
        return $this->lieux_noLieu;
    }

    public function setLieuxNoLieu(?Lieu $lieux_noLieu): self
    {
        $this->lieux_noLieu = $lieux_noLieu;

        return $this;
    }

    public function getEtatsNoEtat(): ?Etat
    {
        return $this->etats_no_etat;
    }

    public function setEtatsNoEtat(?Etat $etats_no_etat): self
    {
        $this->etats_no_etat = $etats_no_etat;

        return $this;
    }

    public function getSiteorganisateur(): ?Site
    {
        return $this->site_organisateur;
    }

    public function setSiteOrganisateur(?Site $site_organisateur): self
    {
        $this->site_organisateur = $site_organisateur;

        return $this;
    }


}

src/Entity/Ville.php
<?php

namespace App\Entity;

use App\Repository\VilleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=VilleRepository::class)
 */
class Ville
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $code_postal;

    /**
     * @ORM\OneToMany(targetEntity=Lieu::class, mappedBy="villes_no_ville")
     */
    private $lieu;

    public function __construct()
    {
        $this->lieu = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->code_postal;
    }

    public function setCodePostal(string $code_postal): self
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    /**
     * @return Collection|Lieu[]
     */
    public function getLieu(): Collection
    {
        return $this->lieu;
    }

    public function addLieu(Lieu $lieu): self
    {
        if (!$this->lieu->contains($lieu)) {
            $this->lieu[] = $lieu;
            $lieu->setVillesNoVille($this);
        }

        return $this;
    }

    public function removeLieu(Lieu $lieu): self
    {
        if ($this->lieu->removeElement($lieu)) {
            // set the owning side to null (unless already changed)
            if ($lieu->getVillesNoVille() === $this) {
                $lieu->setVillesNoVille(null);
            }
        }

        return $this;
    }

    public function __toString(){
        return $this->code_postal . ' - ' . $this->nom;
    }



}

src/Form/SortieType.php
<?php

namespace App\Form;

use App\Entity\Etat;
use App\Entity\Lieu;
use App\Entity\Site;
use App\Entity\Sortie;

use App\Entity\Ville;
use Doctrine\ORM\Mapping\Entity;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ButtonType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;


class SortieType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
//            ->add('url_photo')
            ->add('nom', null, [
                'label' => 'Nom de la sortie'
            ])
            ->add('date_debut', DateTimeType::class, [
                'label' => 'Date et heure de la sortie : ',
                'date_widget' => 'single_text',
            ])
            ->add('date_cloture', DateType::class, [
                'label' => "Date limite d'inscription : ",
                'widget' => 'single_text',
                'required' => false
            ])
            ->add('nb_inscriptions_max', null, [
                'label' => 'Nombre de places : '
            ])

            ->add('duree', null, [
                'label' => 'Durée : '
            ])
            ->add('description_infos', TextareaType::class, [
                'label' => 'Descritpion et infos : '
            ])

            ->add('villes_no_ville', EntityType::class, [
                'class' => Ville::class,
                'placeholder' => 'Sélectionnez une ville',
                'mapped' => false,
                'label' => 'Ville :',
                'required' => false
            ])

            ->add('etats_no_etat', EntityType::class, [
                'class' => Etat::class,
                'label' => 'Etat',
                'choice_label' => 'libelle'
            ])
        ;

        $builder->get('villes_no_ville')->addEventListener(
          FormEvents::POST_SUBMIT,
            function (FormEvent $event)
            {
                $form = $event->getForm();
                $this->addLieuField($form->getParent(), $form->getData());
            });

        $builder->addEventListener(
          FormEvents::POST_SET_DATA,
          function (FormEvent $event){
              $data = $event->getData();
              /* @var $lieu Lieu */
              $lieu = $data->getLieuxNolieu();

              $form = $event->getForm();
              if ($lieu){

                  $ville = $lieu->getVillesNoVille();
                  $this->addLieuField($form, $ville);
                  $form->get('villes_no_ville')->setData($ville);
              }else{
                  $this->addLieuField($form, null);
              }

          }
        );
    }

    private function addLieuField(FormInterface $form, ?Ville $ville){
        $form->add('lieux_noLieu', EntityType::class, [
            'class' => Lieu::class,
            'placeholder' => $ville ? 'Sélectionnez le lieu' : 'Veuillez sélectionner la ville',
            'choices' => $ville ? $ville->getLieu() : [],
            'label' => 'Lieu :'
        ]);
    }


    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Sortie::class,
        ]);
    }
}

templates/sortie/_cancel.html.twig
<form method="post" action="{{ path('sortie_delete', {'id': sortie.id}) }}" onsubmit="return confirm('Êtes-vous sûre de vouloir supprimer cette sortie ?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ sortie.id) }}">
    <button>Annuler</button>
</form>

templates/sortie/_delete_form.html.twig
<form method="post" action="{{ path('sortie_delete', {'id': sortie.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ sortie.id) }}">
    <button class="btn">Delete</button>
</form>

templates/sortie/_form.html.twig
{{ form_start(form) }}
<div class="pure-u-1-5"></div>
<div class="pure-u-1-4">
    {{ form_row(form.nom) }}
    {{ form_row(form.date_debut)}}
    {{ form_row(form.date_cloture)}}
    {{ form_row(form.nb_inscriptions_max)}}
    {{ form_row(form.duree)}}
    {{ form_row(form.description_infos)}}
    
    <br><br><br>
    <button class="btn btn-success button-xlarge">{{ button_label|default('Enregistrer') }}</button>
    &nbsp;&nbsp;&nbsp;
    &nbsp;&nbsp;&nbsp;
    &nbsp;&nbsp;&nbsp;
    <a class = "btn btn-danger button-xlarge" href="{{ path('sortie_index') }}"> Annuler </a>

</div>
<div class="pure-u-1-8"></div>
<div class="pure-u-1-4 pure-form pure-form-stacked">
    Ville Organisatrice : {{ app.user.site.nom}}
    <br><br>
    {{ form_row(form.villes_no_ville)}}
    {{ form_row(form.lieux_noLieu)}}
    <a href="{{ path("lieu_new") }}" class="btn btn-success">Ajouter un lieu <i class="fas fa-plus"></i></a>
    <br><br>
    {{ form_row(form.etats_no_etat)}}

    <script>
        // $(document).ready(function (){
        //     function load
        // })
    </script>

</div>
    {{ form_widget(form) }}

{{ form_end(form) }}

templates/sortie/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Sortie{% endblock %}

{% block body %}

    <div class="pure-u-1-5"></div>
    <div class="pure-u-1-4">
        <h1>Modifier une sortie</h1>
    </div>
    <div class="pure-u-1-5"></div>
    {{ include('sortie/_form.html.twig')}}
   <div class="supprimer"> {{ include('sortie/_delete_form.html.twig') }}</div>

{% endblock %}

templates/sortie/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Accueil{% endblock %}

{% block body %}

    <div id="date">
        Date du jour : {{ "now"|date("d/m/Y") }}
        <br>
        <!-- Nom et prénom de la personne connectée -->
        <!-- nom ? nom et prénom ? pseudo ? -->
        Participant : {{ app.user.prenom }} {{ app.user.nom }}
    </div>

    <!-- 1ère colonne : espacement du bord droit -->
    <div class="pure-u-4-24"></div>
    <!--  2ème colonne : titre -->
    <div class="pure-u-5-24">
        <h1>Filtrer les sorties</h1>
    </div>
    <!-- 3ème colonne : blanc jusqu'au bord gauche -->
    <div class="pure-u-15-24" id="date"></div>
    <br><br>

    <form class="pure-form" action="{{ path('sortie_index') }}" method="POST">
        <!--1ère colonne : espacement du bord droit -->
        <div class="pure-u-4-24"></div>
        <!-- 2ème colonne : champs infos -->
        <div class="pure-u-7-24">
            Site
            <select name="siteNom">            <!-- Liste déroulante des sites -->
                <option selected> </option>
                {% for site in sites %}
                    <option value="{{ site.id }}">{{ site.nom }}</option>
                {% endfor %}
            </select>
            <br>
            <br>
            Le nom de la sortie contient : <input type="text" name="sortieSearch" class="pure-input-rounded"
                                                  placeholder="search"><!-- Input -->
            <br><br>
            Entre <input type="date" name="sortieDate1" value="{{ "now"|date("d/m/Y") }}"> et <input type="date" name="sortieDate2">
        </div>

        <!-- 2ème colonne -->
        <div class="pure-u-5-24">
            <label for="checkbox-radio-option-one" class="pure-checkbox">
                <input type="checkbox" id="checkbox-radio-option-one" name="organisateur"/> Sorties dont je suis
                l'organisateur/trice</label>
            <label for="checkbox-radio-option-two" class="pure-checkbox">
                <input type="checkbox" id="checkbox-radio-option-two" name="inscrit"/> Sorties auxquelles je
                suis
                inscrit/e</label>
            <label for="checkbox-radio-option-three" class="pure-checkbox">
                <input type="checkbox" id="checkbox-radio-option-three" name="nonInscrit"/> Sorties auxquelles
                je ne
                suis pas inscrit/e</label>
            <label for="checkbox-radio-option-four" class="pure-checkbox">
                <input type="checkbox" id="checkbox-radio-option-four" name="sortieEtatPassee"/> Sorties
                passées</label>
        </div>

        <!-- 3ème colonne -->
        <div class="pure-u-5-24">
            <br><br>
            &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;<button
                    class="pure-button pure-button-primary button-xlarge pure-input-rounded">Rechercher
            </button>
        </div>
        </div>
    </form>
    </div>
    <br>

{#    <div class="pure-u-4-24"></div>#}
    <div class="container">
{#    <div class="pure-u-16-24">#}
        <table id="table" class="pure-table pure-table-horizontal">
            <thead>
            <tr>
                <th>Nom de la sortie</th>
                <th>Date de la sortie</th>
                <th>Clôture</th>
                <th>Inscriptions/places</th>
                <th>Etat</th>
                <th>Inscrit</th>
                <th>Organisateur</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for sortie in sorties %}
                <tr>
                    <td>{{ sortie.nom }}</td>
                    <td>{{ sortie.dateDebut ? sortie.dateDebut|date('d/m/Y H:i') : '' }}</td>
                    <td>{{ sortie.dateCloture ? sortie.dateCloture|date('d/m/Y') : '' }}</td>
                    <td>0/{{ sortie.nbInscriptionsMax }}</td>
                    <td>{{ sortie.etatsNoEtat.libelle }}</td>
                    <td>
                        {# {% for sortie in sorties %} #}
                        {% if inscrits %}
                            X
                        {% else %}

                        {% endif %}
                        {# {% endfor %} #}
                    </td>
                    <td>
                        {% if app.user.pseudo is same as (sortie.organisateur.pseudo) %}
                            {{ sortie.organisateur.pseudo }}
                        {% else %}
                            <a href="{{ path('user_controller_index', {'id': sortie.organisateur.id}) }}">{{ sortie.organisateur.pseudo }}</a>
                        {% endif %}
                    </td>
                    <td>
                        <a href="{{ path('sortie_show', {'id': sortie.id}) }}">Afficher</a>
                        {% if (app.user.id == sortie.organisateur.id) %}
                            <a href="{{ path('sortie_edit', {'id': sortie.id}) }}">Modifier</a>
                            {{ include('sortie/_cancel.html.twig') }}
                        {% endif %}
                        {% if (app.user.id != sortie.organisateur.id) %}
                            {% if (date() <= (sortie.dateCloture)) %}
                                <a href="{{ path('sinscrire', {'id': sortie.id}) }}">S'inscrire</a>
                            {% endif %}
                        {% endif %}
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="9">Aucune sortie enregistrée</td>
                </tr>
            {% endfor %}
            </tbody>
    </div>
{#    </div>#}
    </table>
{#    <div class="pure-u-3-24"></div>#}

    <br><br>
    <div class="pure-u-3-24"></div>
    <div class="pure-u-5-24">
        <a class="btn btn-success button-xlarge " href="{{ path('sortie_new') }}">
            Créer une sortie
        </a>&nbsp;
    </div>
    <div class="pure-u-16-24"></div>

{% endblock %}

templates/sortie/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Créer une sortie{% endblock %}


{% block body %}

        <!-- Placeholder text from http://hipsteripsum.me/ -->

                <div class="pure-u-1-5"></div>
                <div class="pure-u-1-4">
                    <h1>Créer une sortie</h1>

                </div>
                <div class="pure-u-1-5"></div>
    {{ include('sortie/_form.html.twig') }}

    {% block javascripts %}
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js"
                integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
    {% endblock %}

{% endblock %}

templates/sortie/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Sortie{% endblock %}

{% block body %}
    <div class="container">

        <h1 class="center">Afficher la sortie</h1>
        <div class="row">
            <div class="col-6">
                <table class="table table-borderless">
                    <tbody>
                    <tr>
                        <th>Nom :</th>
                        <td>{{ sortie.nom }}</td>
                    </tr>
                    <tr>
                        <th>Date et heure de la sortie :</th>
                        <td>{{ sortie.dateDebut ? sortie.dateDebut|date('d/m/Y H:i') : '' }}</td>
                    </tr>
                    <tr>
                        <th>Date limite d'inscription :</th>
                        <td>{{ sortie.dateCloture ? sortie.dateCloture|date('d/m/Y') : '' }}</td>
                    </tr>
                    <tr>
                        <th>Nombre de places :</th>
                        <td>{{ sortie.nbInscriptionsMax }}</td>
                    </tr>
                    <tr>
                        <th>Durée :</th>
                        <td>{{ sortie.duree }} minutes</td>
                    </tr>
                    <tr>
                        <th>Description et infos :</th>
                        <td>{{ sortie.descriptionInfos }}</td>
                    </tr>
                    </tbody>
                </table>
            </div>

            <div class="col-6">
                <table class="table table-borderless">
                    <tbody>
                    <tr>
                        <th>Ville organisatrice :</th>
                        <td>{{ sortie.siteOrganisateur.nom }}</td>
                    </tr>
                    <tr>
                        <th>Ville :</th>
                        <td>{{ sortie.lieuxNoLieu.villesNoVille.nom}}</td>
                    </tr>
                    <tr>
                        <th>Lieu :</th>
                        <td>{{ sortie.lieuxNoLieu.nom }}</td>
                    </tr>
                    <tr>
                        <th>Rue :</th>
                        <td>{{ sortie.lieuxNoLieu.rue }}</td>
                    </tr>
                    <tr>
                        <th>Code postal :</th>
                        <td>{{ sortie.lieuxNoLieu.villesNoVille.codePostal }}</td>
                    </tr>
                    <tr>
                        <th>Latitude :</th>
                        <td>{{ sortie.lieuxNoLieu.latitude }}</td>
                    </tr>
                    <tr>
                        <th>Longitude :</th>
                        <td>{{ sortie.lieuxNoLieu.longitude }}</td>
                    </tr>
                    </tbody>
                </table>
            </div>

            <div class="container">
                <div class="pure-u-7-24">
                    <br><br>
                    <h4>Liste des participants inscrits</h4>
                    <table class="table">
                        <tr>
                            <th>Pseudo</th>
                            <th>Nom et prénom</th>
                        </tr>
                        {% for user in users %}
                            <tr>
{#                                <td>{{ user.pseudo }}</td>#}
                                <td>
                                    {% if app.user.pseudo is same as user.pseudo %}
                                        {{ user.pseudo }}
                                    {% else %}
                                        <a href="{{ path('user_controller_index', {'id': user.id}) }}">{{ user.pseudo }}</a>
                                    {% endif %}
                                </td>
                                <td>{{ user.nom }} {{ user.prenom }}</td>

                            </tr>
                        {% else %}
                            <tr>
                                <td colspan="9">Personne ne s'est actuellement inscrit</td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>

            <div class="container">
                <a href="{{ path('sortie_index') }}"><button class="pure-button button-secondary button-xlarge">Retour</button></a>
                &nbsp;&nbsp;&nbsp;&nbsp;
                {%  if (app.user.id != sortie.organisateur.id) %}
                    {% if (date() <= (sortie.dateCloture)) %}
                        <a href="{{ path('sinscrire', {'id': sortie.id}) }}"><button class="pure-button pure-button-primary">S'inscrire à la sortie</button></a>
                    {% endif %}
                {% endif %}
                {#                {% if(app.user.id == sortie.inscrit) %}#}
                {#                    &nbsp;&nbsp;<a href="{{ path('desister', {'id': sortie.id}) }}') }}"><button class="pure-button pure-button-primary">Se désister</button></a>#}
                {#                {% endif %}#}
                {%  if (app.user.id == sortie.organisateur.id) %}
                    &nbsp;&nbsp;<a href="{{ path('sortie_delete', {'id': sortie.id}) }}" class="btn btn-danger">Annuler la sortie</a>
                {% endif %}

            </div>

        </div>
    </div>
{% endblock %}